// Name: Rahim
// Surname: Rzayev
/* Description: I have given an aplication. This application calculates the duration of sleep from birth.
First, you need to choose birth date and current date. 
You need to touch "calculate" button and then the application is ready to execute.
*/
package start;




/**
 *
 * @author rehim
 */
public class Java_Alive extends javax.swing.JFrame {

    /**
     * Creates new form Java_Alive
     */
    public Java_Alive() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PastYear = new javax.swing.JTextField();
        CurrentYear = new javax.swing.JTextField();
        CurrentMonth = new javax.swing.JTextField();
        CurrentDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PastDay = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        Output = new javax.swing.JTextField();
        ExitApplication = new javax.swing.JButton();
        Title1 = new javax.swing.JLabel();
        Instructions1 = new javax.swing.JLabel();
        Instructions2 = new javax.swing.JLabel();
        Instructions3 = new javax.swing.JLabel();
        Instructions4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PastMonth = new javax.swing.JTextField();
        Output1 = new javax.swing.JTextField();
        Output2 = new javax.swing.JTextField();
        Output3 = new javax.swing.JTextField();
        Output5 = new javax.swing.JTextField();
        Output4 = new javax.swing.JTextField();
        Output6 = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Life Time Recorder by Rahim");
        setBackground(new java.awt.Color(102, 255, 255));

        PastYear.setBackground(new java.awt.Color(204, 204, 204));
        PastYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastYearActionPerformed(evt);
            }
        });

        CurrentYear.setBackground(new java.awt.Color(204, 204, 204));
        CurrentYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentYearActionPerformed(evt);
            }
        });

        CurrentMonth.setBackground(new java.awt.Color(204, 204, 204));
        CurrentMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentMonthActionPerformed(evt);
            }
        });

        CurrentDay.setBackground(new java.awt.Color(204, 204, 204));
        CurrentDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentDayActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Enter Today's Date");

        PastDay.setBackground(new java.awt.Color(204, 204, 204));
        PastDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastDayActionPerformed(evt);
            }
        });

        CalculateButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CalculateButton.setForeground(new java.awt.Color(0, 0, 204));
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        Output.setEditable(false);
        Output.setBackground(new java.awt.Color(204, 204, 255));
        Output.setText(" ");
        Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutputActionPerformed(evt);
            }
        });

        ExitApplication.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitApplication.setForeground(new java.awt.Color(0, 0, 204));
        ExitApplication.setText("Exit Application");
        ExitApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitApplicationActionPerformed(evt);
            }
        });

        Title1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Title1.setForeground(new java.awt.Color(255, 0, 0));
        Title1.setText("Life Time Recorder");

        Instructions1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Instructions1.setForeground(new java.awt.Color(0, 153, 153));
        Instructions1.setText("Enter Your Birthdate");

        Instructions2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Instructions2.setForeground(new java.awt.Color(0, 153, 153));
        Instructions2.setText("Day");

        Instructions3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Instructions3.setForeground(new java.awt.Color(0, 153, 153));
        Instructions3.setText("Month");

        Instructions4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Instructions4.setForeground(new java.awt.Color(0, 153, 153));
        Instructions4.setText("Day");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 153));
        jLabel7.setText("Month");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 153));
        jLabel8.setText("Year");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 153));
        jLabel9.setText("Year");

        PastMonth.setBackground(new java.awt.Color(204, 204, 204));
        PastMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastMonthActionPerformed(evt);
            }
        });

        Output1.setEditable(false);
        Output1.setBackground(new java.awt.Color(204, 204, 255));
        Output1.setText(" ");
        Output1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output1ActionPerformed(evt);
            }
        });

        Output2.setEditable(false);
        Output2.setBackground(new java.awt.Color(204, 204, 255));
        Output2.setText(" ");
        Output2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output2ActionPerformed(evt);
            }
        });

        Output3.setEditable(false);
        Output3.setBackground(new java.awt.Color(204, 204, 255));
        Output3.setText(" ");
        Output3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output3ActionPerformed(evt);
            }
        });

        Output5.setEditable(false);
        Output5.setBackground(new java.awt.Color(204, 204, 255));
        Output5.setText(" ");
        Output5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output5ActionPerformed(evt);
            }
        });

        Output4.setEditable(false);
        Output4.setBackground(new java.awt.Color(204, 204, 255));
        Output4.setText(" ");
        Output4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output4ActionPerformed(evt);
            }
        });

        Output6.setEditable(false);
        Output6.setBackground(new java.awt.Color(204, 204, 255));
        Output6.setText(" ");
        Output6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Output6ActionPerformed(evt);
            }
        });

        Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Reset.setForeground(new java.awt.Color(0, 0, 204));
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Output6, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(605, 605, 605))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Output1)
                                .addComponent(Output)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(232, 232, 232)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Output2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Output3)
                                .addComponent(Output5)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Instructions3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Instructions2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(PastMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PastDay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PastYear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(220, 220, 220))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CalculateButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Reset)
                                            .addGap(111, 111, 111)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ExitApplication)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Instructions4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(CurrentDay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(CurrentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(CurrentYear, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(33, 33, 33))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Output4, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Instructions2)
                            .addComponent(PastDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Instructions4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CurrentDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CurrentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PastMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Instructions3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(PastYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(CurrentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculateButton)
                    .addComponent(ExitApplication)
                    .addComponent(Reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Output1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Output5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(719, 572));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        //Here, I defined what will the program do when the user clicks the component (Calculate) being monitored for an action event.
        
        //create variables and take strings from the box and store them into integers
        //int is written for each variable in order to make sure that variables take into only integer values
        int pastDay = Integer.valueOf(PastDay.getText());    //birth day
        int pastMonth = Integer.valueOf(PastMonth.getText()); //birth ,month
        int pastYear = Integer.valueOf(PastYear.getText());  //birth yeaer
        int currentDay = Integer.valueOf(CurrentDay.getText()); //current day
        int currentMonth = Integer.valueOf(CurrentMonth.getText());//current month
        int currentYear = Integer.valueOf(CurrentYear.getText()); //current year
        // double is written for each variable in order to make sure that variables take into only decimal values
        double age = 0;
        
        // This codes calculate sleeping hours
        int Year = (currentYear - pastYear) * 365;   //number of days between birth year and current year 
        int Months = (currentMonth - pastMonth) * 30; //number of days between birth month and current month 
        int Days = (currentMonth - pastMonth);  //number of days between birth day  and current day 
        int totHours = (Year + Months + Days) * 8; //total number of hours
        
        
        // This code converts hours to seconds
        int totSeconds = (totHours) * 3600;   
               
        // This code converts hours to minutes
        int totMinutes = (totHours) * 60; 

        // This code converts hours to days
        int totDays = (totHours) / 24;
        
        // This code converts hours to weeks
        int totWeeks = (totHours) / 168;
        
        // This code converts hours to months
        int totMonths = (totHours) / 729     ;
        
        // This code converts hours to years
        int totYears = (totHours) / 8766 ;
            
            
        
        
        //calculate the number of days in year, months, days then add them up
        //output it to the textbox
        Output.setText("You have slept for about " + Integer.toString(totHours) + " hours."); //setText()  method here is used to update the text on a , textInput
        
        Output1.setText("You have slept for about " + Integer.toString(totMonths) + " month."); //setText()  method here is used to update the text on a , textInput
        
        Output2.setText("You have slept for about " + Integer.toString(totDays) + " days."); //setText()  method here is used to update the text on a , textInput
        
        Output3.setText("You have slept for about " + Integer.toString(totWeeks) + " weeks."); //setText()  method here is used to update the text on a , textInput
       
        Output4.setText("You have slept for about " + Integer.toString(totSeconds) + " seconds."); //setText()  method here is used to update the text on a , textInput
        
        Output5.setText("You have slept for about " + Integer.toString(totYears) + " years."); //setText()  method here is used to update the text on a , textInput
        
        Output6.setText("You have slept for about " + Integer.toString(totMinutes) + " minutes."); //setText()  method here is used to update the text on a , textInput
      

    }//GEN-LAST:event_CalculateButtonActionPerformed

    private void ExitApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitApplicationActionPerformed
       //Here, I defined what will the program do when the user clicks the component (Exit) being monitored for an action event.
        System.exit(0);
        
    }//GEN-LAST:event_ExitApplicationActionPerformed

    private void PastDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastDayActionPerformed
        // It is in order to choose the date of birth.
    }//GEN-LAST:event_PastDayActionPerformed

    private void PastMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastMonthActionPerformed
         // It is in order to choose the month of birth.
    }//GEN-LAST:event_PastMonthActionPerformed

    private void PastYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastYearActionPerformed
       // It is in order to choose the years of birth.
    }//GEN-LAST:event_PastYearActionPerformed

    private void CurrentMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentMonthActionPerformed
        // It is in order to choose today's month.
    }//GEN-LAST:event_CurrentMonthActionPerformed

    private void CurrentDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentDayActionPerformed
        // It is in order to choose today's date.
    }//GEN-LAST:event_CurrentDayActionPerformed

    private void CurrentYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentYearActionPerformed
        // It is in order to choose today's year.
    }//GEN-LAST:event_CurrentYearActionPerformed

    private void Output1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output1ActionPerformed
        // The output shows resulting number of month
    }//GEN-LAST:event_Output1ActionPerformed

    private void OutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutputActionPerformed
        // The output shows resulting number of hours
    }//GEN-LAST:event_OutputActionPerformed

    private void Output2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output2ActionPerformed
        // The output shows resulting number of days
    }//GEN-LAST:event_Output2ActionPerformed

    private void Output3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output3ActionPerformed
        // The output shows resulting number of weeks
    }//GEN-LAST:event_Output3ActionPerformed

    private void Output5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output5ActionPerformed
        // The output shows resulting number of year
    }//GEN-LAST:event_Output5ActionPerformed

    private void Output4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output4ActionPerformed
        // The output shows resulting number of seconds
    }//GEN-LAST:event_Output4ActionPerformed

    private void Output6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Output6ActionPerformed
        // The output shows resulting number of minutes
    }//GEN-LAST:event_Output6ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        //Here, I defined what will the program do when the user clicks the component (Reset) being monitored for an action event.
        // This button clean all values in the application
        CurrentDay.setText(null);
        CurrentMonth.setText(null);
        CurrentYear.setText(null);
        PastDay.setText(null);
        PastMonth.setText(null);
        PastYear.setText(null);
        Output.setText(null);
        Output1.setText(null);
        Output2.setText(null);
        Output3.setText(null);
        Output4.setText(null);
        Output5.setText(null);
        Output6.setText(null);
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_Alive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_Alive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_Alive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_Alive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_Alive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JTextField CurrentDay;
    private javax.swing.JTextField CurrentMonth;
    private javax.swing.JTextField CurrentYear;
    private javax.swing.JButton ExitApplication;
    private javax.swing.JLabel Instructions1;
    private javax.swing.JLabel Instructions2;
    private javax.swing.JLabel Instructions3;
    private javax.swing.JLabel Instructions4;
    private javax.swing.JTextField Output;
    private javax.swing.JTextField Output1;
    private javax.swing.JTextField Output2;
    private javax.swing.JTextField Output3;
    private javax.swing.JTextField Output4;
    private javax.swing.JTextField Output5;
    private javax.swing.JTextField Output6;
    private javax.swing.JTextField PastDay;
    private javax.swing.JTextField PastMonth;
    private javax.swing.JTextField PastYear;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Title1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
